# DATA PATH
TRAIN_PATH = ""
VALIDATION_PATH = ""
TEST_PATH = ""
LABEL = "sentiments"

# EMBEDDING CONFIG
MAX_LENGTH = 16
EMBEDDING_PATH = ""

# SAVE_FILE
SAVE_PATH = f"fast_svm_{LABEL}_class_weights.pkl"

# MODEL
PCA_COMPONENTS = 800